-- Seed: paises clasificados al Mundial 2022 (32) + extras frecuentes.
-- Puedes adaptar la lista al formato 48 (2026) si lo deseas.
insert into countries (name, fifa_code, flag_url) values
  ('Argentina','ARG','https://flagcdn.com/w160/ar.png'),
  ('Brasil','BRA','https://flagcdn.com/w160/br.png'),
  ('Francia','FRA','https://flagcdn.com/w160/fr.png'),
  ('Alemania','GER','https://flagcdn.com/w160/de.png'),
  ('España','ESP','https://flagcdn.com/w160/es.png'),
  ('Inglaterra','ENG','https://flagcdn.com/w160/gb-eng.png'),
  ('Portugal','POR','https://flagcdn.com/w160/pt.png'),
  ('Países Bajos','NED','https://flagcdn.com/w160/nl.png'),
  ('Bélgica','BEL','https://flagcdn.com/w160/be.png'),
  ('Italia','ITA','https://flagcdn.com/w160/it.png'),
  ('Croacia','CRO','https://flagcdn.com/w160/hr.png'),
  ('Uruguay','URU','https://flagcdn.com/w160/uy.png'),
  ('Colombia','COL','https://flagcdn.com/w160/co.png'),
  ('México','MEX','https://flagcdn.com/w160/mx.png'),
  ('Estados Unidos','USA','https://flagcdn.com/w160/us.png'),
  ('Canadá','CAN','https://flagcdn.com/w160/ca.png'),
  ('Japón','JPN','https://flagcdn.com/w160/jp.png'),
  ('Corea del Sur','KOR','https://flagcdn.com/w160/kr.png'),
  ('Australia','AUS','https://flagcdn.com/w160/au.png'),
  ('Marruecos','MAR','https://flagcdn.com/w160/ma.png'),
  ('Senegal','SEN','https://flagcdn.com/w160/sn.png'),
  ('Ghana','GHA','https://flagcdn.com/w160/gh.png'),
  ('Camerún','CMR','https://flagcdn.com/w160/cm.png'),
  ('Túnez','TUN','https://flagcdn.com/w160/tn.png'),
  ('Polonia','POL','https://flagcdn.com/w160/pl.png'),
  ('Suiza','SUI','https://flagcdn.com/w160/ch.png'),
  ('Serbia','SRB','https://flagcdn.com/w160/rs.png'),
  ('Dinamarca','DEN','https://flagcdn.com/w160/dk.png'),
  ('Gales','WAL','https://flagcdn.com/w160/gb-wls.png'),
  ('Ecuador','ECU','https://flagcdn.com/w160/ec.png'),
  ('Arabia Saudita','KSA','https://flagcdn.com/w160/sa.png'),
  ('Catar','QAT','https://flagcdn.com/w160/qa.png'),
  ('Irán','IRN','https://flagcdn.com/w160/ir.png'),
  ('Costa Rica','CRC','https://flagcdn.com/w160/cr.png'),
  ('Perú','PER','https://flagcdn.com/w160/pe.png'),
  ('Chile','CHI','https://flagcdn.com/w160/cl.png'),
  ('Paraguay','PAR','https://flagcdn.com/w160/py.png'),
  ('Bolivia','BOL','https://flagcdn.com/w160/bo.png'),
  ('Venezuela','VEN','https://flagcdn.com/w160/ve.png'),
  ('Egipto','EGY','https://flagcdn.com/w160/eg.png'),
  ('Argelia','ALG','https://flagcdn.com/w160/dz.png'),
  ('Nigeria','NGA','https://flagcdn.com/w160/ng.png'),
  ('Costa de Marfil','CIV','https://flagcdn.com/w160/ci.png'),
  ('Sudáfrica','RSA','https://flagcdn.com/w160/za.png'),
  ('Turquía','TUR','https://flagcdn.com/w160/tr.png'),
  ('Suecia','SWE','https://flagcdn.com/w160/se.png'),
  ('Noruega','NOR','https://flagcdn.com/w160/no.png'),
  ('Austria','AUT','https://flagcdn.com/w160/at.png')
on conflict (name) do nothing;
